# Generated by Django 5.1.6 on 2025-02-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0002_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='employee',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='attendance_delay',
        ),
    ]
