# Generated by Django 5.1.6 on 2025-02-27 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0003_rename_employee_notification_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='emergency_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_details.emergencycontact'),
        ),
    ]
