# Generated by Django 5.1.6 on 2025-02-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0005_remove_employeedetails_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='emergency_contact',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
