# Generated by Django 5.1.6 on 2025-02-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0006_remove_employeedetails_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='employee_address',
            new_name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='earned_leave',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='leave_description',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='office_grace_time',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='office_in_time',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='office_out_time',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='office_regular_time',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='sick_leave',
        ),
    ]
