# Generated by Django 5.1.6 on 2025-02-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0007_rename_employee_address_employeedetails_permanent_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=255)),
                ('interview_date', models.DateTimeField()),
                ('interview_result', models.TextField()),
                ('interview_notes', models.TextField(blank=True, null=True)),
                ('interview_pdf', models.FileField(blank=True, null=True, upload_to='interviews/')),
            ],
        ),
    ]
