# Generated by Django 5.1.6 on 2025-03-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0008_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cv_file', models.FileField(upload_to='cv_files/')),
                ('letter_type', models.CharField(choices=[('Offer Letter', 'Offer Letter'), ('Appointment Letter', 'Appointment Letter'), ('Joining Report', 'Joining Report')], max_length=50)),
            ],
        ),
    ]
