# Generated by Django 5.1.6 on 2025-03-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0009_cvmanagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvmanagement',
            name='cv_file',
        ),
        migrations.AddField(
            model_name='cvmanagement',
            name='letter_file',
            field=models.FileField(blank=True, null=True, upload_to='letters/'),
        ),
    ]
