# Generated by Django 5.1.6 on 2025-03-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0010_remove_cvmanagement_cv_file_cvmanagement_letter_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmanagement',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
