# Generated by Django 5.1.6 on 2025-03-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0011_alter_cvmanagement_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='name',
            new_name='employee',
        ),
    ]
