# Generated by Django 5.1.6 on 2025-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0013_cvadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=255)),
                ('bank_account_paper', models.BooleanField(default=False)),
                ('sim_card', models.BooleanField(default=False)),
                ('visiting_card', models.BooleanField(default=False)),
                ('placement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payroll_pdf', models.FileField(blank=True, null=True, upload_to='payrolls/')),
            ],
        ),
        migrations.CreateModel(
            name='ITProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=255)),
                ('id_card', models.BooleanField(default=False)),
                ('laptop', models.BooleanField(default=False)),
            ],
        ),
    ]
