# Generated by Django 5.1.6 on 2025-03-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0014_adminprovision_financeprovision_itprovision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeprovision',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_details.employeedetails'),
        ),
    ]
