# Generated by Django 5.1.6 on 2025-03-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0016_alter_cvmanagement_letter_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeprovision',
            name='employee',
            field=models.CharField(max_length=255),
        ),
    ]
