# Generated by Django 5.1.6 on 2025-03-04 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0017_alter_financeprovision_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(default=datetime.time(9, 30)),
        ),
        migrations.AlterField(
            model_name='financeprovision',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='financeprovision',
            name='payroll_pdf',
            field=models.FileField(upload_to='payroll_pdfs/'),
        ),
    ]
