# Generated by Django 5.1.6 on 2025-03-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0018_alter_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_delay',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(),
        ),
    ]
