# Generated by Django 5.1.6 on 2025-03-04 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0019_remove_attendance_attendance_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='office_start_time',
            field=models.TimeField(default=datetime.time(9, 30)),
        ),
    ]
