# Generated by Django 5.1.6 on 2025-03-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0024_employeeattachment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TADGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('TEXWEAVE', 'TEXWEAVE'), ('TAD SOURCE', 'TAD SOURCE'), ('TAD LOGISTIC', 'TAD LOGISTIC'), ('KOITHE', 'KOITHE'), ('KLOTHEN', 'KLOTHEN')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_details.tadgroup'),
        ),
    ]
