# Generated by Django 5.1.6 on 2025-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0025_tadgroup_employeedetails_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadgroup',
            name='company',
            field=models.CharField(choices=[('TEXWEAVE', 'TEXWEAVE'), ('TAD SOURCING', 'TAD SOURCING'), ('TAD LOGISTIC', 'TAD LOGISTIC'), ('KOITHE', 'KOITHE'), ('KLOTHEN', 'KLOTHEN')], max_length=50),
        ),
    ]
