# Generated by Django 5.1.6 on 2025-03-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0027_alter_employeedetails_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='company',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='tadgroup',
            name='company',
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='image1',
            field=models.ImageField(upload_to='employee_images/'),
        ),
    ]
