# Generated by Django 5.1.6 on 2025-03-08 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0028_rename_company_employeedetails_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='group',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_details.tadgroup'),
        ),
        migrations.AddField(
            model_name='tadgroup',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
