# Generated by Django 5.1.6 on 2025-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0029_remove_employeedetails_group_employeedetails_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadgroup',
            name='name',
            field=models.CharField(blank=True, default='Unnamed Group', max_length=255, unique=True),
        ),
    ]
