# Generated by Django 5.1.6 on 2025-03-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0030_alter_tadgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
