# Generated by Django 5.1.6 on 2025-03-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0031_alter_tadgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadgroup',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
