# Generated by Django 5.1.6 on 2025-03-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0032_alter_tadgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='company',
        ),
        migrations.DeleteModel(
            name='TADGroup',
        ),
    ]
