# Generated by Django 5.1.6 on 2025-03-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0033_remove_employeedetails_company_delete_tadgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TADGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
    ]
