# Generated by Django 5.1.6 on 2025-03-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0035_rename_company_name_tadgroups_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee_details.tadgroups'),
        ),
    ]
