# Generated by Django 5.1.6 on 2025-03-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0036_employeedetails_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tadgroups',
            old_name='company',
            new_name='company_name',
        ),
    ]
