# Generated by Django 5.1.6 on 2025-03-11 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0039_terminationattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminationattachment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_details.employeedetails'),
        ),
        migrations.AlterField(
            model_name='terminationattachment',
            name='file',
            field=models.FileField(upload_to='termination_attachments/'),
        ),
    ]
