# Generated by Django 5.1.6 on 2025-03-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0041_cvadd_age_cvadd_email_cvadd_phone_cvadd_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interview_notes',
            new_name='interview_questions',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='candidate',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interview_pdf',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interview_result',
        ),
        migrations.AddField(
            model_name='interview',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='clarity_of_communication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='cultural_fit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='english_proficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='good_behaviour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewee_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviwe_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='relevant_skills',
            field=models.BooleanField(default=False),
        ),
    ]
