# Generated by Django 5.1.6 on 2025-03-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0042_rename_interview_notes_interview_interview_questions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interviwe_mark',
            new_name='interview_mark',
        ),
    ]
