# Generated by Django 5.1.6 on 2025-03-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0044_interview_interview_notes_interview_interview_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mdsir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
