# Generated by Django 5.1.6 on 2025-03-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0045_mdsir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdsir',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
