# Generated by Django 5.1.6 on 2025-03-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0046_alter_mdsir_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdsir',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
