# Generated by Django 5.1.6 on 2025-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0047_mdsir_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdsir',
            name='description',
        ),
        migrations.AddField(
            model_name='mdsir',
            name='interview_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
