# Generated by Django 5.1.6 on 2025-03-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0048_remove_mdsir_description_mdsir_interview_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_detailss', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
