# Generated by Django 5.1.6 on 2025-03-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0049_invitemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitemail',
            old_name='interview_detailss',
            new_name='interview_details',
        ),
    ]
