# Generated by Django 5.1.6 on 2025-03-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0050_rename_interview_detailss_invitemail_interview_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVManagement',
            new_name='LetterSend',
        ),
    ]
