# Generated by Django 5.1.6 on 2025-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0052_remove_interview_clarity_of_communication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvadd',
            name='position_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='position_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
