# Generated by Django 5.1.6 on 2025-03-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0053_cvadd_position_for_interview_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='current_remuneration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='expected_package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='immediate_recruitment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='no_good',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='notice_period_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
