# Generated by Django 5.1.6 on 2025-03-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0055_interview_final_selection_remakrs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='final_selection_remakrs',
            new_name='final_selection_remarks',
        ),
    ]
