# Generated by Django 5.1.6 on 2025-03-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0056_rename_final_selection_remakrs_interview_final_selection_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanseAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('last_increment_date', models.DateField()),
                ('last_promotion_date', models.DateField()),
                ('last_education', models.CharField(max_length=255)),
                ('appraisal_result', models.CharField(max_length=255)),
                ('appraisal_date', models.DateField()),
                ('performance_score', models.IntegerField()),
                ('feedback', models.TextField()),
                ('training_needs', models.TextField()),
                ('promotion_recommendation', models.TextField()),
                ('job_knowledge', models.IntegerField()),
                ('performance_in_meetings', models.IntegerField()),
                ('communication_skills', models.IntegerField()),
                ('reliability', models.IntegerField()),
                ('initiative', models.IntegerField()),
                ('stress_management', models.IntegerField()),
                ('co_operation', models.IntegerField()),
                ('leadership', models.IntegerField()),
                ('discipline', models.IntegerField()),
                ('ethical_considerations', models.IntegerField()),
            ],
        ),
    ]
