# Generated by Django 5.1.6 on 2025-03-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0057_performanseappraisal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanseappraisal',
            name='appraisal_date',
        ),
        migrations.RemoveField(
            model_name='performanseappraisal',
            name='appraisal_result',
        ),
        migrations.RemoveField(
            model_name='performanseappraisal',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='performanseappraisal',
            name='performance_score',
        ),
        migrations.RemoveField(
            model_name='performanseappraisal',
            name='promotion_recommendation',
        ),
        migrations.RemoveField(
            model_name='performanseappraisal',
            name='training_needs',
        ),
        migrations.AddField(
            model_name='performanseappraisal',
            name='co_operation_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanseappraisal',
            name='communication_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanseappraisal',
            name='discipline_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanseappraisal',
            name='ethical_considerations_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanseappraisal',
            name='initiative_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanseappraisal',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanseappraisal',
            name='leadership_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanseappraisal',
            name='performance_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanseappraisal',
            name='reliability_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanseappraisal',
            name='stress_management_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
