# Generated by Django 5.1.6 on 2025-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0059_performanseappraisal_expected_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanseappraisal',
            name='performance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='co_operation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='communication_skills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='discipline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='ethical_considerations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='increment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='initiative',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='job_knowledge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='leadership',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='performance_in_meetings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='performance_reward',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='promotion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='reliability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='stress_management',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
