# Generated by Django 5.1.6 on 2025-04-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0060_performanseappraisal_performance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Public_Festival_Holiday', models.ImageField(upload_to='')),
                ('Casual_Leave', models.ImageField(upload_to='')),
                ('Sick_Leave', models.ImageField(upload_to='')),
                ('Earned_Leave', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('public_festival_holiday', 'Public Festival Holiday'), ('casual_leave', 'Casual Leave'), ('sick_leave', 'Sick Leave'), ('earned_leave', 'Earned Leave')], max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_details.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_festival_holiday', models.IntegerField(default=0)),
                ('casual_leave', models.IntegerField(default=0)),
                ('sick_leave', models.IntegerField(default=0)),
                ('earned_leave', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_details.employeedetails')),
            ],
        ),
    ]
