# Generated by Django 5.1.6 on 2025-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0061_employeeleavetype_employeeleave_employeeleavebalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleavetype',
            name='Casual_Leave',
        ),
        migrations.RemoveField(
            model_name='employeeleavetype',
            name='Earned_Leave',
        ),
        migrations.RemoveField(
            model_name='employeeleavetype',
            name='Public_Festival_Holiday',
        ),
        migrations.RemoveField(
            model_name='employeeleavetype',
            name='Sick_Leave',
        ),
        migrations.AddField(
            model_name='employeeleavetype',
            name='casual_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeleavetype',
            name='earned_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeleavetype',
            name='public_festival_holiday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeleavetype',
            name='sick_leave',
            field=models.IntegerField(default=0),
        ),
    ]
