# Generated by Django 5.1.6 on 2025-04-08 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0062_remove_employeeleavetype_casual_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='actual_date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_employees', to='employee_details.tadgroups'),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='date_of_joining_after_leave',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_applied_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_availed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_entited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='reson_for_delay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='sub_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
