# Generated by Django 5.1.6 on 2025-04-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0064_employeeleave_employee_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
