# Generated by Django 5.1.6 on 2025-04-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0065_employeeleave_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleave',
            name='leave_applied_for',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='leave_availed',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='leave_balance',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='leave_entited',
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='leave_balance',
            field=models.IntegerField(default=0),
        ),
    ]
