# Generated by Django 5.1.6 on 2025-04-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0066_remove_employeeleave_leave_applied_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('public_festival_holiday', 'Public Festival Holiday'), ('casual_leave', 'Casual Leave'), ('sick_leave', 'Sick Leave'), ('earned_leave', 'Earned Leave')], max_length=255, null=True),
        ),
    ]
