# Generated by Django 5.1.6 on 2025-04-09 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0067_alter_employeeleave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_details.tadgroups'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
