# Generated by Django 5.1.6 on 2025-04-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0068_alter_employeeleave_company_alter_employeeleave_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
