# Generated by Django 5.1.6 on 2025-04-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0069_employeeleave_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavebalance',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
