# Generated by Django 5.1.6 on 2025-04-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0071_alter_employeedetails_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='image1',
            field=models.ImageField(upload_to='employee_images/'),
        ),
    ]
