# Generated by Django 5.1.6 on 2025-04-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0072_alter_employeedetails_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interview_questions',
        ),
        migrations.AddField(
            model_name='attendance',
            name='delay_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
