# Generated by Django 5.1.6 on 2025-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0073_remove_interview_interview_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
