# Generated by Django 5.1.6 on 2025-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0074_employeeleave_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/'),
        ),
    ]
