# Generated by Django 5.1.6 on 2025-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0076_alter_employeedetails_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='reporting_leader',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
