# Generated by Django 5.1.6 on 2025-04-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0077_alter_employeedetails_reporting_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
    ]
