# Generated by Django 5.1.6 on 2025-04-17 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0078_hr_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hr_Email',
        ),
    ]
