# Generated by Django 5.1.6 on 2025-04-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0079_delete_hr_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='customer',
            field=models.CharField(blank=True, null=True),
        ),
    ]
