# Generated by Django 5.1.6 on 2025-04-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0080_employeedetails_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='customer',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='customer',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employee_details.customers'),
        ),
    ]
