# Generated by Django 5.1.6 on 2025-04-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0081_customers_remove_employeedetails_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='name',
            new_name='customer_name',
        ),
    ]
