# Generated by Django 5.1.6 on 2025-04-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0082_rename_name_customers_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='hrcomment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='teamleader',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='whereabouts',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
