# Generated by Django 5.1.6 on 2025-04-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0083_employeeleave_hrcomment_employeeleave_teamleader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='hrcomment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='teamleader',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
