# Generated by Django 5.1.6 on 2025-04-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0084_employeeleave_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='cc',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
