# Generated by Django 5.1.6 on 2025-05-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='cm_price',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='fabric_consumption',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='fabric_price',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='fub_in_dz',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='fub_pace',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='order_qty',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='other_price',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='printing_price',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='washing_price',
        ),
    ]
