# Generated by Django 5.1.6 on 2025-05-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0002_remove_inquiry_cm_price_remove_inquiry_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='color',
            field=models.ManyToManyField(blank=True, to='merchandiser.color'),
        ),
    ]
