# Generated by Django 5.1.6 on 2025-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0003_inquiry_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsizegroup',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='inquiries_as_color', to='merchandiser.colorsizegroup'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='color_size_groups',
            field=models.ManyToManyField(blank=True, related_name='inquiries_as_group', to='merchandiser.colorsizegroup'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
