# Generated by Django 5.1.6 on 2025-05-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0004_alter_colorsizegroup_color_alter_inquiry_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='colorsizegroup',
            name='color',
        ),
        migrations.AddField(
            model_name='colorsizegroup',
            name='color',
            field=models.ManyToManyField(blank=True, to='merchandiser.color'),
        ),
    ]
