# Generated by Django 5.1.6 on 2025-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0005_color_remove_colorsizegroup_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorsizegroup',
            name='color',
        ),
        migrations.AddField(
            model_name='colorsizegroup',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
