# Generated by Django 5.1.6 on 2025-05-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0006_remove_colorsizegroup_color_colorsizegroup_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='color',
        ),
        migrations.AlterField(
            model_name='colorsizegroup',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchandiser.color'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='color_size_groups',
            field=models.ManyToManyField(blank=True, to='merchandiser.colorsizegroup'),
        ),
    ]
