# Generated by Django 5.1.6 on 2025-05-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0008_alter_inquiry_year_delete_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SizeRange',
        ),
        migrations.DeleteModel(
            name='TotalAccessories',
        ),
    ]
