# Generated by Django 5.1.6 on 2025-05-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0009_delete_sizerange_delete_totalaccessories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='name',
            new_name='names',
        ),
    ]
