# Generated by Django 5.1.6 on 2025-05-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0010_rename_name_buyer_names'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer',
            new_name='Buyers',
        ),
    ]
