# Generated by Django 5.1.6 on 2025-05-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0011_rename_buyer_buyers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyers',
            new_name='Buyer',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='names',
            new_name='name',
        ),
    ]
