# Generated by Django 5.1.6 on 2025-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0012_rename_buyers_buyer_rename_names_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='order_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
