# Generated by Django 5.1.6 on 2025-05-27 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0013_inquiry_order_no_inquiry_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inquiries/attachments/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='merchandiser.inquiry')),
            ],
        ),
    ]
