# Generated by Django 5.1.6 on 2025-05-27 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0014_inquiryattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='inquiries/attachments/'),
        ),
        migrations.AlterField(
            model_name='inquiryattachment',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='merchandiser.inquiry'),
        ),
    ]
